name: C++ Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest # Using Ubuntu for Linux build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Project with Make
      working-directory: ./Linux/build # Ensure we are in the correct build directory
      run: make # This will run 'make' within the Linux/build directory

    # You might want to add steps for:
    # - Packaging artifacts
    # - Uploading build artifacts
    # - Running linters/code analysis
