name: C++ Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest # Using Ubuntu for Linux build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install libjpeg-dev
      run: sudo apt-get install -y libjpeg-dev
    
    - name: clean up build
      working-directory: ./
      run: find . -name "*.o" -type f -delete

    - name: Build Project with Make
      working-directory: ./Linux/build # Ensure we are in the correct build directory
      run: make clean && make

    - name: Build react_on_object_detect
      working-directory: ./Linux/project/gwenski/react_on_object_detect
      run: make clean && make

    # You might want to add steps for:
    # - Packaging artifacts
    # - Uploading build artifacts
    # - Running linters/code analysis
