name: C++ Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest # Using Ubuntu for Linux build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install libjpeg-dev
      run: sudo apt-get install -y libjpeg-dev
    
    - name: clean up build
      working-directory: ./
      run: find . -name "*.o" -type f -delete

    - name: Build Project with Make
      working-directory: ./Linux/build # Ensure we are in the correct build directory
      run: make clean && make
      
    - name: Create and Upload Main Project Artifact
      uses: actions/upload-artifact@v4
      with:
        name: darwin-main-build-linux
        path: ./Linux/build/

  
